name: Release to GHCR

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml

jobs:
  release:
    name: Build & Push to GHCR using pyproject version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      GHCR_IMAGE: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if pyproject.toml version changed
        id: check
        run: |
          git diff HEAD^ HEAD pyproject.toml | grep "^+version" || echo "NO_VERSION_CHANGE=true" >> $GITHUB_ENV

      - name: Exit if no version change
        if: env.NO_VERSION_CHANGE == 'true' && github.ref_type != 'tag'
        run: |
          echo "No version change in pyproject.toml. Skipping workflow."
          exit 0

      - name: Extract version from pyproject.toml
        id: version
        run: |
          VERSION=$(grep -Po '(?<=^version = ")[^"]+' pyproject.toml)
          echo "VERSION=$VERSION"
          echo "VERSION_TAG=v$VERSION" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployments/docker/Dockerfile
          push: true
          tags: |
            ${{ env.GHCR_IMAGE }}:${{ env.VERSION_TAG }}
