name: fastapi-house-price lint-and-test

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    name: Lint & Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.1.1 flake8_black==0.3.6
          pip install pytest pandas joblib scikit-learn

      - name: Lint with flake8
        run: |
          flake8 --max-line-length=119 \
                 --ignore=E722,I201,I100,BLK100,W503 \
                 --per-file-ignores=__init__.py:F401 \
                 main.py

      - name: Run Unit Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/test_model_correctness.py
